#!/bin/bash
# List of Pokémon to fetch      
pokemon_list=("Bulbasaur" "Ivysaur" "Venusaur" "Charmander" "Charmeleon")
for pokemon in "${pokemon_list[@]}"; do
    (
        curl -s "https://pokeapi.co/api/v2/pokemon/${pokemon,,}" -o "${pokemon}.json"
    ) &
done
wait
echo "All Pokémon data fetched."

